name: research_ugc
version: '3.9'

services:
  zookeeper-vertica:
    image: zookeeper:3.8.3
    container_name: zookeeper-vertica
    hostname: zookeeper

  clickhouse-node1:
    image: clickhouse/clickhouse-server:23
    container_name: clickhouse-node1
    hostname: clickhouse-node1
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./ugc-service/data/node1:/etc/clickhouse-server
      - ./ugc-service/data/node1:/docker-entrypoint-initdb.d
    depends_on:
      - zookeeper-vertica
    healthcheck:
      test: ["CMD", "clickhouse-client", "--query", "SELECT 1"]
      interval: 10s
      timeout: 3s
      retries: 3

  clickhouse-node2:
    image: clickhouse/clickhouse-server:23
    container_name: clickhouse-node2
    hostname: clickhouse-node2
    ports:
      - "8124:8123"
      - "9001:9000"
    volumes:
      - ./ugc-service/data/node2:/etc/clickhouse-server
      - ./ugc-service/data/node2:/docker-entrypoint-initdb.d
    depends_on:
      - zookeeper-vertica

  clickhouse-node3:
    image: clickhouse/clickhouse-server:23
    container_name: clickhouse-node3
    hostname: clickhouse-node3
    ports:
      - "8125:8123"
      - "9002:9000"
    volumes:
      - ./ugc-service/data/node3:/etc/clickhouse-server
      - ./ugc-service/data/node3:/docker-entrypoint-initdb.d
    depends_on:
      - zookeeper-vertica

  clickhouse-node4:
    image: clickhouse/clickhouse-server:23
    container_name: clickhouse-node4
    hostname: clickhouse-node4
    ports:
      - "8126:8123"
      - "9003:9000"
    volumes:
      - ./ugc-service/data/node4:/etc/clickhouse-server
      - ./ugc-service/data/node4:/docker-entrypoint-initdb.d
    depends_on:
      - zookeeper-vertica

  vertica:
    image: jbfavre/vertica:latest
    container_name: vertica
    ports:
      - "5433:5433"
    healthcheck:
      test: ["CMD", "vsql", "-U", "dbadmin", "-w", "", "-c", "SELECT 1;"]
      interval: 10s
      timeout: 3s
      retries: 3
