@startuml
skinparam componentStyle uml2
component AuthService
component MoviesService
actor User as Client
component FastapiUGC
component Openapi
component DjangoAdminPanel
database PostgresUGC
database Redis
database Cassandra
database Kafka

Client -down-> MoviesService: Запрос пользователя на сайте/приложении
MoviesService <-left-> AuthService: Получение токена пользователя
MoviesService <-down-> FastapiUGC: Запрос.
FastapiUGC -> PostgresUGC: CRUD действие согласно запроса
FastapiUGC <-down-> Cassandra: Пока не понятно
FastapiUGC <-down-> Kafka: Запись/чтение действий пользователя
FastapiUGC <-down-> Redis: Запись/чтение состояний.

DjangoAdminPanel -down-> PostgresUGC: CRUD
Openapi -right-> FastapiUGC: Документация API
@enduml
