name: research_ugc
version: '3.9'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:23
    ports:
      - "8123:8123"
      - "9000:9000"

  vertica:
    image: jbfavre/vertica:latest
    container_name: vertica
    ports:
      - "5433:5433"
