"""review

Revision ID: 1f29ba7b1121
Revises: e875680d71f6
Create Date: 2024-02-14 12:46:38.455819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1f29ba7b1121"
down_revision: Union[str, None] = "e875680d71f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_film_review",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("film_id", sa.UUID(), nullable=False),
        sa.Column("review", sa.Text(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("modified_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "film_id", name="unique_reviev_from_user_to_film"
        ),
    )
    op.create_unique_constraint(None, "user_film_like", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_film_like", type_="unique")
    op.drop_table("user_film_review")
    # ### end Alembic commands ###
